version: '2'

services:
  wordpress:
    build: ./
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_PASSWORD: examplepass
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/smaily-woocommerce-plugin

  wordpress_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: examplepass
    volumes:
      - wordpress_db:/var/lib/mysql
volumes:
  wordpress:
  wordpress_db:
