version: '2'

services:
  wordpress:
    build: ./
    restart: always
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: smailydev1
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_DISPLAY', true);
        define('WP_DEBUG_LOG', '/dev/stderr');
    volumes:
    - wordpress:/var/www/html
    - ./:/var/www/html/wp-content/plugins/smaily-woocommerce-plugin

  wordpress_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: smailydev1
    volumes:
    - wordpress_db:/var/lib/mysql
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677

  phpmyadmin:
    depends_on:
    - wordpress_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - '8888:80'
    environment:
      PMA_HOST: wordpress_db
      PMA_USER: root
      PMA_PASSWORD: smailydev1
      MYSQL_ROOT_PASSWORD: smailydev1

volumes:
  wordpress:
  wordpress_db:
